### ISSUE TITLE
[0.4.1] Skyblock/Void not being created on a server

### ISSUE THREAD

**Issue by TigerWalts** [MSandro/NeoForge-Foundry-SkyBlock-Edition#1]
The `level-type` is not being set to `exdeorum:void` when a new world is created.

The Ex Deorum is meant to override the level type by default but in this modpack it fails. Running a server with just Ex Deorum fails to create the skyblock world. So another mod is overriding this behaviour.

Setting the `level-type` in `server.properties` to `exdeorum:void` or any other value has no effect.

**Comment by MSandro** [comment]
I can not reproduce this issue in 0.4.1, the server file should be approved soon.
![image](https://github.com/MSandro/NeoForge-Foundry-SkyBlock-Edition/assets/10937159/fc2ec0c6-c815-4930-8536-3af872cb40ae)

**Comment by TigerWalts** [comment]
I found the cause.

Ex Deorum will only create the Skyblock/Void world on a server if there is no `server.properties` file.

I'll take the issue to them.

**Comment by TigerWalts** [comment]
For information, setting the level-type in the server.properties to the correct value of `exdeorum:void_world` will work.

If the file exists and it either has no level-type set, or has a different level-type set then it will not work.
