### ISSUE TITLE
Crash on startup, similar to Stoneblock version

### ISSUE THREAD

**Issue by DJDrWright** [MSandro/NeoForge-Foundry-SkyBlock-Edition#2]
Version 0.4.1. Error is java.lang.IllegalArgumentException: No model for layer twilightforest:knightmetal_shield#main

Crash report attached
[crash-2024-04-26_06.29.41-client.txt](https://github.com/MSandro/NeoForge-Foundry-SkyBlock-Edition/files/15130003/crash-2024-04-26_06.29.41-client.txt)

**Comment by MSandro** [comment]
Strange, could you please Check if Modern UI Mod is installed, if yes please remove it and try again.

**Comment by DJDrWright** [comment]
It is not, first thing I checked. I updated modernfix to latest version and that fixed it.

**Comment by MSandro** [comment]
Great to know, but we are not able to release the next update before monday.

**Comment by MSandro** [comment]
fixed in 0.4.2 by updating ModernFix
