### ISSUE TITLE
Crash on start: Rendersystem called from wrong thread

### ISSUE THREAD

**Issue by TiphaineLAURENT** [MSandro/NeoForge-Foundry-SkyBlock-Edition#3]
I recently started playing NeoForge Foundry: SkyBlock Edition.
After a first session without issues (wooden shears do not seems to work on leaves but I might just be bad), I restarted the game and it crashed.
I tried a few more times and it is always the same error: Rendersystem called from wrong thread

I a playing on the 0.4.1 version from curseforge.

[latest.log](https://github.com/MSandro/NeoForge-Foundry-SkyBlock-Edition/files/15131243/latest.log)

**Comment by 0gp** [comment]
Since 0.4.2 I can play it again, did it fix the problem for you too?

**Comment by TiphaineLAURENT** [comment]
I just did a test sessions and it seems fixed. Thanks

**Comment by TiphaineLAURENT** [comment]
I just did a test sessions and it seems fixed. Thanks
