### ISSUE TITLE
Steam Age Progression Issue 

### ISSUE THREAD

**Issue by Umbra540** [MSandro/NeoForge-Foundry-SkyBlock-Edition#4]
In Steam Age the Bronze that it requires is Mekanism not modern industries which prevents you from using the quest log until you have unlocked Mekanism.

**Comment by MSandro** [comment]
Mekanism Bronze can be Obtained with Bronze Dust, just combine Copper and Tin Dusts in the Crafting Table to get Bronze Dust (MI), it will be smelted to Mekanism Bronze Ingot.

**Comment by Umbra540** [comment]
That might be the intended way but there is currently no configuration for that in version 0.4.1 I have checked the recipe for that particular type of Bronze and there is no way to make it before you get a metallurgic infuser.

![BronzeCraft](https://github.com/MSandro/NeoForge-Foundry-SkyBlock-Edition/assets/32114782/e69592cf-7eec-4668-8065-3437e6ce2404)
![BronzeRecipie](https://github.com/MSandro/NeoForge-Foundry-SkyBlock-Edition/assets/32114782/88e86870-1037-4f86-acd5-c0cd579fd1e2)

**Comment by 0gp** [comment]
Step 1: get some Tin and Copper and crush it to dust in the Forge Hammer:
![grafik](https://github.com/MSandro/NeoForge-Foundry-SkyBlock-Edition/assets/62187599/d0a92c53-b026-47b3-adf3-68133234a6a1)

Step 2: craft Bronze Dust
![grafik](https://github.com/MSandro/NeoForge-Foundry-SkyBlock-Edition/assets/62187599/4ae8eded-e82a-40c0-8c54-1913d8965595)

Step 3: smelt the Bronze Dust [MI] to Bronze Ingots [Mekanism]
![grafik](https://github.com/MSandro/NeoForge-Foundry-SkyBlock-Edition/assets/62187599/47b144d5-ba68-4320-b6ce-3b5c7cdb5640)

I don't see the problem.

**Comment by MSandro** [comment]
I know there were problems with antimony and bauxite, but with bronze everything should be fine.
I close this issue. If there really is a problem, feel free to open it again.
